###############################################################
#  Generated by:      Cadence Innovus 19.11-s128_1
#  OS:                Linux x86_64(Host ID cn92.it.auth.gr)
#  Generated on:      Mon Dec  5 22:26:00 2022
#  Design:            picorv32
#  Command:           create_ccopt_clock_tree_spec -file ./Desktop/asic/prj/ino/ex1_14/cre_clk_tree1.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 10.000ns) in timing_config Const1([/mnt/scratch_b/users/d/dimitriosa/Desktop/asic/prj/ino/designs/picorv32.dat/mmmc/modes/Const1/Const1.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner1 -early -clock_tree clk 0.100

set_ccopt_property target_max_trans_sdc -delay_corner DelayCorner1 -late -clock_tree clk 0.100
set_ccopt_property source_driver -clock_tree clk {BUFX2/A BUFX2/Y}
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 10

# Skew group to balance non generated clock:clk in timing_config:Const1 (sdc /mnt/scratch_b/users/d/dimitriosa/Desktop/asic/prj/ino/designs/picorv32.dat/mmmc/modes/Const1/Const1.sdc)
create_ccopt_skew_group -name clk/Const1 -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Const1 true
set_ccopt_property extracted_from_clock_name -skew_group clk/Const1 clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Const1 Const1
set_ccopt_property extracted_from_delay_corners -skew_group clk/Const1 {DelayCorner1 DelayCorner1}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

